### ISSUE TITLE
Review for CD needed

### ISSUE THREAD

**Issue by aminadinari19** [aminadinari19/SaveOurTime#30]
This is not an issue rather a request. The CD branch is up and running with the help of @odiisus. Please take a look at the new pull request and let us know if any issue is encountered.

**Comment by Abanoubr** [comment]
Hi @aminadinari19 

I found this error
Error: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}

I think we should discuss it in today's meeting

**Comment by Abanoubr** [comment]
But everything else seems to be running smooth tho

**Comment by aminadinari19** [comment]
Checked and working on it :)
